### ISSUE TITLE
update outputs in pipeline interface

### ISSUE THREAD

**Issue by nsheff** [databio/peppro#18] opened 2019-08-09 20:17 UTC
[2019-08-09 16:15:03,970] {looper:438} (create_project_objects) [WARNING] > Summarizer was unable to find: Library complexity file (summary/ppqc_libComplexity.pdf) 
[2019-08-09 16:15:03,970] {looper:438} (create_project_objects) [WARNING] > Summarizer was unable to find: Library complexity file (summary/ppqc_libComplexity.pdf) 

the outputs are incomplete.

**Comment by jpsmith5** [comment] 2019-11-27 17:22
This is working as intended.  If the library complexity file is not made, there won't be an output from it.  Not aware of a way to make a Summarizer only function if it's target file is present via Looper. Closing for now unless there is a way or we decide to make a way to do so.

**Closed by jpsmith5** 2019-11-27 17:22 UTC
Labels: bug
