### ISSUE TITLE
bowtie2 error results are not logged to primary log

### ISSUE THREAD

**Issue by nsheff** [databio/peppro#14] opened 2019-08-01 18:44 UTC
Here we're redirectoring error output into a file:

https://github.com/databio/peppro/blob/4283767e032cd45d8b14457106befa6b5227c340/pipelines/peppro.py#L1141-L1142

That's fine...but now if this errors, you dont' see why:

```

### Map to human_rDNA (08-01 14:42:48) elapsed: 0.0 _TIME_

Found lock file: /home/nsheff/code/peppro/peppro_test/results_pipeline/test/lock.prealignments__test_human_rDNA_unmap.fq.gz
Overwriting target. . .
Target to produce: `/home/nsheff/code/peppro/peppro_test/results_pipeline/test/prealignments/test_human_rDNA_unmap.fq.gz`


> `(bowtie2 -p 8 -k 1 -D 20 -R 3 -N 1 -L 20 -i S,1,0.50 -x /project/shefflab/genomes/human_rDNA/bowtie2_index/human_rDNA --rg-id test -U /home/nsheff/code/peppro/peppro_test/results_pipeline/test/fastq/test_R1_processed.fastq --un /home/nsheff/code/peppro/peppro_test/results_pipeline/test/prealignments/test_human_rDNA_unmap.fq > /dev/null) 2>/home/nsheff/code/peppro/peppro_test/results_pipeline/test/prealignments/test_human_rDNA_bt_aln_summary.log` (9037)

<pre>
</pre>
Process 9037 returned 2; memory: 0.018GB.  Elapsed: 0:00:01. Peak memory: 0.018GB.

Conditional flag found: []

These conditional files were left in place:

- /home/nsheff/code/peppro/peppro_test/results_pipeline/test/fastq/test*.fastq
- /home/nsheff/code/peppro/peppro_test/results_pipeline/test/fastq/*.fq
- /home/nsheff/code/peppro/peppro_test/results_pipeline/test/fastq/*.fastq
- /home/nsheff/code/peppro/peppro_test/results_pipeline/test/fastq/*.log
- /home/nsheff/code/peppro/peppro_test/results_pipeline/test/fastq/test_R1_noadap.fastq
- /home/nsheff/code/peppro/peppro_test/results_pipeline/test/fastq/test_R1_dedup.fastq
- /home/nsheff/code/peppro/peppro_test/results_pipeline/test/fastq/test_R1_trimmed.fastq
- /home/nsheff/code/peppro/peppro_test/results_pipeline/test/prealignments/tmpyotzgh07

### Pipeline failed at:  (08-01 14:42:49) elapsed: 1.0 _TIME_

Total time: 0:00:01

Changed status from running to failed.
Traceback (most recent call last):
  File "pipelines/peppro.py", line 2965, in <module>
    sys.exit(main())
  File "pipelines/peppro.py", line 1719, in main
    aligndir="prealignments")
  File "pipelines/peppro.py", line 1161, in _align_with_bt2
    pm.run(cmd, out_fastq_tmp_gz)
  File "/home/nsheff/.local/lib/python3.7/site-packages/pypiper/manager.py", line 756, in run
    self.callprint(cmd, shell, lock_file, nofail, container)  # Run command
  File "/home/nsheff/.local/lib/python3.7/site-packages/pypiper/manager.py", line 967, in callprint
    self._triage_error(SubprocessError(msg), nofail)
  File "/home/nsheff/.local/lib/python3.7/site-packages/pypiper/manager.py", line 1970, in _triage_error
    self.fail_pipeline(e)
  File "/home/nsheff/.local/lib/python3.7/site-packages/pypiper/manager.py", line 1556, in fail_pipeline
    raise e
pypiper.exceptions.SubprocessError: Subprocess returned nonzero result. Check above output for details

```

I have to look at that file to see the rror:

```
cat /home/nsheff/code/peppro/peppro_test/results_pipeline/test/prealignments/test_human_rDNA_bt_aln_summary.log
(ERR): "/project/shefflab/genomes/human_rDNA/bowtie2_index/human_rDNA" does not exist or is not a Bowtie 2 index
Exiting now ...
```

is there a reason we want this logged to its own log instead of the main pipeline log?

**Comment by jpsmith5** [comment] 2019-08-01 19:41
I was doing it this way because I use the summary_file (that output) to identify reads that aligned exactly.  This was the result from early issues with the ATAC-seq pipeline not reporting all the read metrics in a way that correctly identified those reads that were removed nor allowed someone to add up all the individual values and arrive at the original read count number.

**Comment by jpsmith5** [comment] 2019-11-27 18:52
Working as intended. Closing for now, but can decide differently in the future.

**Closed by jpsmith5** 2019-11-27 18:52 UTC

**Comment by nsheff** [comment] 2019-11-27 22:13
I see what you mean, but I think it's equally as important that the bowtie output end up in the logs, as well... is there a way to do both? use `tee`?
